# Generated by Django 5.1.4 on 2025-01-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0003_vendor_date_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.jpg', upload_to='user_directroy_path'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐★☆☆'), (4, '⭐⭐⭐⭐☆'), (3, '⭐⭐⭐★☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
