# Generated by Django 5.1.4 on 2025-01-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0004_vendor_cover_image_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('process', 'Processing'), ('shipped', 'Shipped')], default='Processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐★☆☆'), (3, '⭐⭐⭐★☆'), (5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆')], default=None),
        ),
    ]
