# Generated by Django 5.1.4 on 2025-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0006_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default='10', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='Organic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valid',
            field=models.CharField(blank=True, default='100 Days', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐★☆☆'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐★☆')], default=None),
        ),
    ]
