# Generated by Django 5.1.4 on 2025-01-21 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0011_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('in_review', 'In Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='martApp.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐★☆'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆'), (2, '⭐⭐★☆☆')], default=None),
        ),
    ]
