# Generated by Django 5.1.4 on 2025-01-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0012_address_mobail_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (4, '⭐⭐⭐⭐☆'), (3, '⭐⭐⭐★☆'), (2, '⭐⭐★☆☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
