# Generated by Django 5.1.4 on 2025-01-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0013_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': 'Cart Order Items'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐★☆☆'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆'), (3, '⭐⭐⭐★☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
