# Generated by Django 5.1.4 on 2025-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0014_alter_cartorderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('process', 'Processing')], default='Processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('draft', 'Draft'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐★☆☆'), (1, '⭐☆☆☆☆'), (4, '⭐⭐⭐⭐☆'), (3, '⭐⭐⭐★☆')], default=None),
        ),
    ]
