# Generated by Django 5.1.4 on 2025-01-24 16:50

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0018_cartorder_saved_cartorder_shipping_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=5, max_length=20, null=True, prefix='OID'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('process', 'Processing'), ('shipped', 'Shipped')], default='Processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=5, max_length=20, null=True, prefix='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐★☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐★☆☆'), (4, '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
