# Generated by Django 5.1.4 on 2025-01-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0019_rename_name_cartorder_full_name_cartorder_oid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('process', 'Processing')], default='Processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐★☆'), (2, '⭐⭐★☆☆'), (4, '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
