# Generated by Django 5.1.4 on 2025-01-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0021_cartorder_coupons_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'In Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐★☆'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐★☆☆')], default=None),
        ),
    ]
