# Generated by Django 5.1.4 on 2025-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0022_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐★☆☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐☆'), (3, '⭐⭐⭐★☆')], default=None),
        ),
    ]
