# Generated by Django 5.1.4 on 2025-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0023_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐★☆'), (2, '⭐⭐★☆☆'), (1, '⭐☆☆☆☆'), (4, '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
