# Generated by Django 5.1.4 on 2025-01-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0024_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐★☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐★☆☆'), (4, '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
